### ISSUE TITLE
Suggestion: "Spiral Calendar" emoji for journals

### ISSUE THREAD

**Issue by paulrudy** [blueteafrog/logseq-mocha-theme#3]
Just a suggestion: My eye is often drawn to the date in the calendar emoji that precedes daily journal titles. I've changed it in my `custom.css` to:

```css
.journal-title .title::before,
.is-journals .title::before {
	content: "🗓️" !important;
}
```

Perhaps it might make sense to use that as the theme default?
